name: Java CI with Gradle
on: [ push, pull_request ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'oracle'
                    java-version: '21'
                    cache: 'gradle'
            -   name: Make gradlew executable
                run: chmod +x ./gradlew
            -   name: Run build with Gradle wrapper
                run: ./gradlew build
            -   name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v3
                env:
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

